baseURL = "/"
themesDir = "themes"
theme = "hugo-serif-theme"
languageCode = "en-us"
title = "DERIVA"

[module]

  [module.hugoVersion]
    extended = true
    min = "0.119.0"


[params]
  # In most cases you will only want to set the google_analytics_id OR the google_tag_manager_id. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = "G-CR4LB09N1X"
  google_tag_manager_id = ""
  favicon = "favicon.png"

  # One or many extra style sheets you want injected in <head>.
  # The paths are relative to /static or the project root.
  customCSS = ["css/custom.css", "css/publications.css"]

  [params.homepage]
    sticky_header = false
    show_contact_box = false      # show / hide the contaxt box on the homepage
    show_services_button = true # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/logo.png"
    mobile_height = "36px"
    desktop = "images/logo/logo.png"
    desktop_height = "100px"
    alt = "DERIVA - a data-centric asset management platform designed to support scientific collaboration through the full lifecycle of data"

  [params.fonts]
  # Google Fonts request for Inter (400 regular & 600 semi-bold)
  google_fonts = "https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap"

  # Tell the theme which families to use
  heading      = "Inter"
  base         = "Inter"

  [params.colors]
    primary = "#237d9e"
    secondary = "#CBE28E"
    black = "#2f2f41"
    white = "#ffffff"
    white_offset = "#f6f7ff"
    grey = "#5C5A5A"

  [params.seo]
#    meta_twitter_site = "@zerostaticio"
#    meta_twitter_creator = "@zerostaticio"
#    meta_og_image = "https://www.zerostatic.io/theme/hugo-serif/hugo-serif-screenshot.png"

  [params.services]
    summary_truncate = 120 # How many characters to include in the summary of the services before truncating

  [params.team]
    summary_large_truncate = 120 # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = 'Copyright 2025, USC Information Sciences Institute, Informatics Systems Research Division'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Overview"
    url = "/deriva/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name  = "Tools"
    url   = "/tools/"
    weight = 4

  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 5

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6

  # Footer Menu
  [[menu.footer]]
    name = "Contact Us"
    url = "/contact/"
    weight = 1

  [[menu.footer]]
    name = "Privacy Policy"
    url = "/privacy/"
    weight = 2

  [markup]
    [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe = true
